language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.1.8
    - DJANGO_VERSION=2.2.1
branches:
    except:
        - media
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -e .
    - pip install -q selenium
    - pip install -q coveralls
script:
    - coverage run --source publications --omit publications/six.py publications/tests/__main__.py
after_success:
    - coveralls
