language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
env:
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
    - DJANGO_VERSION=1.7.1
matrix:
    exclude:
        - python: "2.6"
          env: DJANGO_VERSION=1.7.1
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -e .
    - pip install -q coveralls
script:
    - coverage run --source publications publications/tests/__main__.py
after_success:
    - coveralls
