language: python
python:
    - "3.3"
    - "2.7"
    - "2.6"
env:
    - DJANGO_VERSION=1.4.0
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
    - DJANGO_VERSION=1.7.1
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -e .
script:
    - python publications/tests
