language: python
python:
    - "2.7"
    - "3.4"
env:
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.0
    - DJANGO_VERSION=1.9.9
    - DJANGO_VERSION=1.10.2
branches:
    except:
        - media
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -e .
    - pip install -q selenium
    - pip install -q coveralls
script:
    - coverage run --source publications --omit publications/six.py publications/tests/__main__.py
after_success:
    - coveralls
